### ISSUE TITLE
Wrong answer in code that uses shared memory

### ISSUE THREAD

**Issue by elliottslaughter** [cpc/hipcl#18]
I've got a code that gets the right answer with AMD HIP, but the wrong answer with HIPCL. The only thing that's really interesting about this code is that it uses shared memory; in all other respects it seems pretty simple.

I'm running this on a testbed system at Argonne National Laboratory where HIPCL is pre-installed. The version is 0.9. I can ask the admins for more details about the installation if that is important.

You can find the reproducer below. Instructions to build and run are included in the README in the same directory. Note again that these instructions are intended for ANL's system, but hopefully it's easy to see how to adapt it to your own environment.

https://github.com/ExaFEL/gpu-portability-samples/tree/iris-hip-histogram-repro/hip

The offending code is `histogram`. On an AMD system, I get the final answer:

```
total = 1048576 (PASS)
```

With HIPCL I get:

```
total = 0 (FAIL)
```

Somehow, I seem not to be getting the histogram results copied back at all.

**Comment by franz** [comment]
I've looked into this, and this should have been fixed by commit 4de6c1f22e718398a (already merged into master), can you retest ?

**Comment by zjin-lcf** [comment]
It passes the test for me.

**Comment by elliottslaughter** [comment]
Also confirmed. Thank you!
