### ISSUE TITLE
invalid memory release at the end of the execution of the program

### ISSUE THREAD

**Issue by zjin-lcf** [cpc/hipcl#2]
I modified the stream example in HIP-examples (https://github.com/ROCm-Developer-Tools/HIP-Examples/tree/master/add4)  to make it run using hipcl. I think there is some issue (bug) about the memory release at the end of the execution of the program.  I attached the reproducer for you.

Thank you
[hipcl-examples-master-add4_hipcl.zip](https://github.com/cpc/hipcl/files/3795230/hipcl-examples-master-add4_hipcl.zip)

**Comment by franz** [comment]
Hi,

I've reproduced the bug, and it should be fixed in master branch now.

I also had to change the Makefile to properly build against hipcl, you can find it [here](https://gist.github.com/franz/fd160b2360ac95007792c547ef572317). (requires editing the paths at the top)
