### ISSUE TITLE
clEnqueueSVMMemCopy() failed with error -5

### ISSUE THREAD

**Issue by zjin-lcf** [cpc/hipcl#22]
The reproducer is https://github.com/zjin-lcf/oneAPI-DirectProgramming/tree/master/transpose-hip

**Comment by franz** [comment]
This sounds exactly like the bug in Intel GPU driver, which we discussed some time ago.

The gist is that clEnqueueSVMMemcpy works if the source buffer is on stack or heap, but fails with -5 (CL_OUT_OF_RESOURCES) if it's static / const (stored in the ELF binary).

You could try updating your Intel GPU drivers to see if they fixed this, but there's nothing hipcl can do about this bug.

**Comment by Kerilk** [comment]
I observed the same behavior on our recently updated systems. So I can safely say that Intel did not fix this bug. I'll make a reproducer for this and report it to Intel.

**Comment by zjin-lcf** [comment]
Thanks again.

**Comment by franz** [comment]
@Kerilk FYI reproducer was already made and sent to Intel. And i think they've been aware of the issue for a while, because other people have also ran into it:

https://github.com/boostorg/compute/issues/818

**Comment by Kerilk** [comment]
Do you have the reproducer somewhere? I'd like the bug to be in our own Intel-ANL bug trackers. Maybe I have a better chance to get them moving this way.

**Comment by franz** [comment]
@Kerilk  [here it is](https://gist.github.com/franz/476dfe6aa59b4e8e36878236576cdc91)
