### ISSUE TITLE
atomics results mismatch

### ISSUE THREAD

**Issue by zjin-lcf** [cpc/hipcl#25]
Please verify if the results are reproducible for https://github.com/zjin-lcf/oneAPI-DirectProgramming/tree/master/atomicIntrinsics-hip

Add failed 1342177280 0
Sub failed: -1342177280 0
Max failed: 134217727 -256
Min failed: 0 256
And failed: 1 255

**Comment by franz** [comment]
Can't reproduce, works with both Intel CPU & GPU for me.
