### ISSUE TITLE
atomicAdd accumulates garbage in billions of iterations

### ISSUE THREAD

**Issue by dizcza** [cpc/hipcl#30]
Hi again,

I've ported my application to HIPCL to work with the shared rather than constant memory, I was using `hipify-clang` applied onto my CUDA source code.
I noticed a strange behavior while accumulating many floats via the `atomicAdd` function. Here is the code. I stripped off the complexity to something you can easily digest. Note that the original CUDA source code works fine.
```c
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#include <assert.h>
#include <float.h>
#include <limits.h>

#include <hip/hip_runtime.h>


#define N_THREADS        32
#define ITERATIONS_TODO  (1LL << 37)  // a very large number
#define ULL              unsigned long long


#define gpuErrchk(ans) { gpuAssert((ans), __FILE__, __LINE__); }
inline void gpuAssert(hipError_t code, const char *file, int line)
{
   if (code != hipSuccess) 
   {
      fprintf(stderr,"GPUassert: %s %s %d\n", hipGetErrorString(code), file, line);
   }
}



__global__ void addManyFloatsKernel(float *P_out) {
    unsigned int row;
   
    // Although in the particular example shared memory
    // can be static (32 floats), the real application
    // I'm using requires dynamic shared mem.
    HIP_DYNAMIC_SHARED(float, shared_mem);
    float *P_shared = (float*)shared_mem;  // 32 floats
    P_shared[threadIdx.x] = 0; 

    __syncthreads();

    const ULL burnout = blockIdx.x * blockDim.x + threadIdx.x;
    const ULL stride = gridDim.x * blockDim.x;  // 65536 * 32

    ULL iteration;
    for (iteration = burnout; iteration < ITERATIONS_TODO; iteration += stride) {
        // Add a small number - the value does not matter
        atomicAdd(P_shared + threadIdx.x, exp(-20.0f));
    }

    __syncthreads();

    atomicAdd(P_out + threadIdx.x, P_shared[threadIdx.x]);
}



int main(int argc, char* argv[]) {
    // An array of size N_THREADS, for simplicity.
    float P_total[N_THREADS];
    float *P_total_device;

    // Initialize P_total_device with zeros.
    // Values other than 0x00 or 0xFF (NaN) won't work
    gpuErrchk( hipMalloc((void**)&P_total_device, sizeof(float) * N_THREADS) );
    gpuErrchk( hipMemset(P_total_device, 0, sizeof(float) * N_THREADS) );

    const ULL grid_size = 65536;  // max available
    const unsigned long shared_mem_used = sizeof(float) * N_THREADS;
    
    hipLaunchKernelGGL(addManyFloatsKernel, dim3(grid_size), dim3(N_THREADS), shared_mem_used, 0, P_total_device);
    gpuErrchk( hipPeekAtLastError() );
    
    // If you uncomment this line, the run will never complete.
    // gpuErrchk( hipDeviceSynchronize() );

    // Transfer data back to host memory
    gpuErrchk( hipMemcpy(P_total, P_total_device, sizeof(float) * N_THREADS, hipMemcpyDeviceToHost) );

    hipFree(P_total_device);

    printf(">>> P_total\n");
    int i;
    for (i = 0; i < N_THREADS; i++) {
        printf("%.7f ", P_total[i]);
    }
    printf("\n");
    
    return 0;
}
```

Expected behavior: the program prints an array of *the same* floating-point values. For example, when `ITERATIONS_TODO` is small (say `1<<32`), the program correctly outputs
```
>>> P_total
0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 0.2766289 
```

## Part 1
The issue appears when I crank up the number of iterations, `ITERATIONS_TODO`, to higher values (`1 << 37` almost always reproduces the bug). The higher the value, the higher the probability to catch the bug - the nature of this bug is *stochastic*, not deterministic. Smaller iterations will certainly work, and the user won't see the bug. Large values will certainly show the issue by printing some garbage, an example of which:
```
>>> P_total
0.0000000 0.0000000 106698129357259381229822698061824.0000000 0.0000000 0.0000000 0.0000000 75273761322601607104563349815296.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531 0.1361531
```
The output is incorrect because *all* values must be the same - by the logic I've designed in the kernel.

## Part 2
Another issue I encountered when I wanted to see what type of error the backend experiences, but if I uncomment the line
```
    // gpuErrchk( hipDeviceSynchronize() );
```
the program hangs forever. These issues are surely related. Note that `hipMemcpy` is (must be) a blocking command, therefore
```
    gpuErrchk( hipMemcpy(P_total, P_total_device, sizeof(float) * N_THREADS, hipMemcpyDeviceToHost) );
```
must produce the same behavior as in `gpuErrchk( hipDeviceSynchronize() )` (according to a CUDA guide), but it doesn't - it ignores the errors encountered in a kernel.

Best,
Danylo

## How to build

Assuming you copied the example above in `hipcl_sharedmem_bug.hip` (although the problem could be not in the shared memory atomic additions),

```
# /root/llvm/build/bin/clang++ -pthread -fPIE -O3 -g -std=c++11 `/root/hipcl/build/bin/hipcl_config -C`  -o hipcl_sharedmem_bug.o hipcl_sharedmem_bug.hip -Wl,-rpath,/root/hipcl/build/lib -L/root/hipcl/build/lib -lhipcl
# ./hipcl_sharedmem_bug.o
```

## Hardware

Intel Corporation UHD Graphics 620.
```
# /root/hipcl/build/bin/samples/hipInfo 
--------------------------------------------------------------------------------
device#                           0
Name:                             Intel(R) Gen9 HD Graphics NEO
pciBusID:                         16
pciDeviceID:                      64
multiProcessorCount:              24
maxThreadsPerMultiProcessor:      10
isMultiGpuBoard:                  0
clockRate:                        1150 Mhz
memoryClockRate:                  1 Mhz
memoryBusWidth:                   256
clockInstructionRate:             2.465 Mhz
totalGlobalMem:                   12.35 GB
maxSharedMemoryPerMultiProcessor: 0.00 GB
totalConstMem:                    4294959104
sharedMemPerBlock:                64.00 KB
regsPerBlock:                     64
warpSize:                         0
l2CacheSize:                      524288
computeMode:                      0
maxThreadsPerBlock:               256
maxThreadsDim.x:                  256
maxThreadsDim.y:                  256
maxThreadsDim.z:                  256
maxGridSize.x:                    65536
maxGridSize.y:                    65536
maxGridSize.z:                    65536
major:                            2
minor:                            0
concurrentKernels:                1
arch.hasGlobalInt32Atomics:       1
arch.hasGlobalFloatAtomicExch:    0
arch.hasSharedInt32Atomics:       1
arch.hasSharedFloatAtomicExch:    0
arch.hasFloatAtomicAdd:           0
arch.hasGlobalInt64Atomics:       1
arch.hasSharedInt64Atomics:       1
arch.hasDoubles:                  1
arch.hasWarpVote:                 0
arch.hasWarpBallot:               0
arch.hasWarpShuffle:              0
arch.hasFunnelShift:              0
arch.hasThreadFenceSystem:        0
arch.hasSyncThreadsExt:           0
arch.hasSurfaceFuncs:             0
arch.has3dGrid:                   0
arch.hasDynamicParallelism:       0
gcnArch:                          0
peers:                            device#0 
non-peers:                        

memInfo.total:                    12.35 GB
memInfo.free:                     12.35 GB (100%)
```

**Comment by dizcza** [comment]
I've ported my application to PyOpenCL and see similar if not exact buggy behavior. I suppose it's due to not officially supported atomic add instructions for floats and doubles. People have come up with many workarounds but they all fail (I've checked every example I've found) to work when the number of iterations is huge as in this example. Floats are "more stable" than doubles but they also give up after a million additions (a billion divided by the threads count).

There is a promise in OpenCL 2.x and 3.0 where more effort is shown towards atomic operations for (double) floating-point values, but they still don't provide API for `atomic_add`. I wonder, what people do about it - it's strange to believe that atomic reductions are not commonly used in millions of additions and yet I've never encountered any comments saying that all these atomic add workarounds are unstable...

**Comment by franz** [comment]
Hello,

just a quick comment (currently busy with different project).

The `atomicAdd` on floats does not exist on AMD hardware, and also OpenCL does not define it (it only defines atomic ops on integers). The way `atomicAdd` is done, is emulation by a while loop with an atomic compare-exchange. IIRC the algorithm in hipcl is copied verbatim from AMD's HIP headers.

I doubt there is any obvious problem in atomicAdd algorithm (i suspect it would be discovered by now), it's likely something else - hipcl, intel's OpenCL implementation, intel hardware. There is a way to test if this is a hipcl bug - rewrite the test in OpenCL and see if it hangs with intel OpenCL too.

**Comment by zjin-lcf** [comment]
> I've ported my application to PyOpenCL and see similar if not exact buggy behavior. I suppose it's due to not officially supported atomic add instructions for floats and doubles. People have come up with many workarounds but they all fail (I've checked every example I've found) to work when the number of iterations is huge as in this example. Floats are "more stable" than doubles but they also give up after a million additions (a billion divided by the threads count).
> 
> There is a promise in OpenCL 2.x and 3.0 where more effort is shown towards atomic operations for (double) floating-point values, but they still don't provide API for `atomic_add`. I wonder, what people do about it - it's strange to believe that atomic reductions are not commonly used in millions of additions and yet I've never encountered any comments saying that all these atomic add workarounds are unstable...

Could you please provide an OpenCL example equivalent to your HIP example ?

**Comment by franz** [comment]
@dizcza actually i just remembered one small thing: the intel GPU driver has a feature called "hangcheck". If you run kernels that take "too long", it thinks you've managed to hang the GPU, and it resets the hardware. That would explain why you get garbage data / hangs but only with larger number of iterations. This should be trivial to check: if the driver resets the GPU, there should be some message in the kernel logs.

**Comment by Kerilk** [comment]
The feature is described here:
https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-oneapi-base-linux/top/before-you-begin.html
in the `GPU: Disable Hangcheck` section.

**Comment by dizcza** [comment]
Amazing, thank you very much for this information! Disabling GPU Hangcheck solved the problem here and in PyOpenCL implementation. I was looking in the wrong direction...
You've saved days if not weeks of my time because I was thinking that there is a bug in the Intel NEO driver I'm using, and I was reading OpenCL extensively to find possible ways why this issue might occur. I didn't even consider that there might be such a safety check in Intel GPU cards, which, of course, is reasonable to have once I start thinking of it. I wonder if Nvidia GPU cards have a similar safety check...
Thank you again.

Best,
Danylo
