### ISSUE TITLE
__byte_perm question

### ISSUE THREAD

**Issue by zjin-lcf** [cpc/hipcl#36]
@franz 

Should the implementation of the function be like this: 

unsigned int __byte_perm2(unsigned int x, unsigned int y, unsigned int s) {
  struct uchar2Holder cHoldVal;
  struct ucharHolder cHoldKey;
  struct ucharHolder cHoldOut;
  cHoldVal.ui[0] = x;
  cHoldVal.ui[1] = y;
  cHoldOut.c[0] = cHoldVal.c[s & 0x7];
  cHoldOut.c[1] = cHoldVal.c[(s >> 4) & 0x7];
  cHoldOut.c[2] = cHoldVal.c[(s >> 8) & 0x7];
  cHoldOut.c[3] = cHoldVal.c[(s >> 12) & 0x7];
  return cHoldOut.ui;
}

**Comment by pjaaskel** [comment]
Thanks - this is better, but seems to assume a little-endian target device. I'm not sure if big endian is used anywhere in GPU world any more, but could you add a macro check and #error out there if BE? OpenCL has a macro for that: 
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/preprocessorDirectives.html \_\_ENDIAN\_LITTLE\_\_

Also C99 standard seems to not guarantee the layout of objects, if I've understood it correctly, thus the union-based casting might not be the most portable, but again, likely not causing problems in practice.
