### ISSUE TITLE
__syncwarp from HIP to OpenCL 

### ISSUE THREAD

**Issue by zjin-lcf** [cpc/hipcl#6]
As far as I know, Intel OpenCL has an __syncwarp() equivalent. I attached a HIP example for you to consider adding the support in HIPCL.  Thanks.

[warp_sync.txt](https://github.com/cpc/hipcl/files/4513630/warp_sync.txt)

**Comment by pjaaskel** [comment]
I suggest you to send a PR if you need it quickly since we must focus on another project for some time due to an urgent deadline.

**Comment by zjin-lcf** [comment]
I don't know how many projects you are working on. Thanks for letting me know your urgent project deadline.

**Comment by zjin-lcf** [comment]
Sorry, __syncwarp() is not supported by HIP.
