### ISSUE TITLE
math.h file not found

### ISSUE THREAD

**Issue by Philius** [cpc/hipcl#7]
make
[ 46%] Built target hipSYCL_cpu
[ 50%] Building CXX object src/sycl/CMakeFiles/hipSYCL_cuda.dir/application.cpp.o
In file included from <built-in>:1:
In file included from /usr/lib/llvm-10/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:36:
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath:45:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated when compiling for sm_52.
make[2]: *** [src/sycl/CMakeFiles/hipSYCL_cuda.dir/build.make:63: src/sycl/CMakeFiles/hipSYCL_cuda.dir/application.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:190: src/sycl/CMakeFiles/hipSYCL_cuda.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Compilation previously failed with libdevice sm_52 not found which I worked around by adding  -nocudalib to the cuda target compile options.

I'm running Debian Bullseye.

**Comment by zjin-lcf** [comment]
Is this for hipSYCL  or HIPCL ?

**Comment by Philius** [comment]
`[ 46%] Built target hipSYCL_cpu`
so, hipSYCL.

**Comment by Philius** [comment]
Wait... how'd I end up on hipCL?

**Comment by Philius** [comment]
Sorry, I must have been on autopilot - closing.
